### ISSUE TITLE
Width = 0 of terminal control characters

### ISSUE THREAD

**Issue by martinheidegger** [tokuhirom/visualwidth-js#2]
Terminal control characters are characters that add color to text or make it bold in the terminal context. Visualwidth is an *awesome* tool that lets me figure out the size of characters in the console. I thought it might be a good place to ask for support of 0(zero) sized characters in terminals.

**Comment by tokuhirom** [comment]
patches welcome

**Comment by martinheidegger** [comment]
Closed in favour of PR #3
