### ISSUE TITLE
Difference to wcwidth

### ISSUE THREAD

**Issue by martinheidegger** [tokuhirom/visualwidth-js#9]
https://github.com/timoxley/wcwidth seems to implement the same (or similar) logic in a way that most terminals do. May I ask why you chose to implement your own logic?

**Comment by tokuhirom** [comment]
i don't know that module.

**Comment by martinheidegger** [comment]
I checked the module and code and found that the difference is that wcwidth is an _exact_ way to identify the characters in a terminal (it is the base for various terminal implementation) while it looks like visualwidth-js assume two width characters based on other fonts. i.e.: "…" is double-width in `visualwidth-js` while it is single-width in a terminal and also in `wcwidth`.
